pipeline {
    agent {
        node {
            label 'maven'
        }
    }
    environment {
        APP_NAMESPACE = 'palpbr-security-scans'
    }
    stages {
        stage('Test') {
            steps {
                dir('shopping-cart') {
                    script {
                        sh './mvnw clean test'
                    }
                }
            }
        }
        stage('Image Build') {
            steps {
                dir('shopping-cart') {
                    script {
                        sh """
                        oc start-build security-scans \
                            --follow --wait -n ${env.APP_NAMESPACE}
                        """
                    }
                }
            }
        }
        stage('Security Scan') {
            steps {
                dir('shopping-cart') {
                    script {
                        sh """
                        oc process -f kubefiles/security-scan-template.yml \
                            -n ${env.APP_NAMESPACE} \
                            -p PROJECT_NAME=${env.APP_NAMESPACE} \
                            -p CVE_CODE=CVE-2020-14583 \
                            | oc replace --force -n ${env.APP_NAMESPACE} -f -
                        """
                        sh "! ../tools/check-job-state.sh security-scans-trivy ${env.APP_NAMESPACE}"
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('shopping-cart') {
                    script {
                        sh """
                        oc patch deployment security-scans \
                            -p '{"spec": {"template": {"metadata": {"labels": {"build": "build-$ {BUILD_NUMBER}"}}}}}' \
                            -n ${env.APP_NAMESPACE}
                        """
                    }
                }
            }
        }
    }
}

