apiVersion: v1
kind: Template
metadata:
  name: home-automation-template
  annotations:
    description: "Home Automation Application Template"
objects:
<<<<<<< HEAD
  - kind: Deployment
    apiVersion: apps/v1
=======
  - kind: DeploymentConfig
    apiVersion: v1
>>>>>>> cd26c9ed54c0d8e5c46dbf1be2517a20f4d7f9a1
    metadata:
      name: home-automation
    spec:
      selector:
<<<<<<< HEAD
        matchLabels:
          app: home-automation
=======
        app: home-automation
>>>>>>> cd26c9ed54c0d8e5c46dbf1be2517a20f4d7f9a1
      replicas: 1
      template:
        metadata:
          labels:
            app: home-automation
        spec:
          containers:
            - name: home-automation
              image: quay.io/${QUAY_USER_OR_GROUP}/${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
      strategy:
<<<<<<< HEAD
        type: RollingUpdate
=======
        type: Rolling
>>>>>>> cd26c9ed54c0d8e5c46dbf1be2517a20f4d7f9a1
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: home-automation
      name: home-automation
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: home-automation
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: home-automation
      labels:
        app: home-automation
    spec:
      to:
        kind: Service
        name: home-automation
      port:
        targetPort: 8080

parameters:
  - name: QUAY_USER_OR_GROUP
    description: "Quay User/Group"
    required: true
  - name: APP_IMAGE_NAME
    description: "Image Name"
    required: false
    value: "home-automation"
  - name: APP_IMAGE_TAG
    description: "Image Tag"
    required: false
<<<<<<< HEAD
    value: "latest"
=======
    value: "latest"
>>>>>>> cd26c9ed54c0d8e5c46dbf1be2517a20f4d7f9a1
